# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#for zsh completions
fpath=(/usr/local/share/zsh-completions $fpath)

# Customize to your needs...
#Hack to stop Zshell from renaming tmux
DISABLE_AUTO_TITLE=true

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

alias apt='sudo aptitude install'
alias yummy='sudo yum install'
alias up='sudo aptitude update && sudo aptitude safe-upgrade'
alias search='sudo apt-cache search'
alias la='ls -a'
alias ..='cd ..'
alias code='cd ~/Code/'

#get to the dreamhost SSH!
alias dream='ssh alxjrvs@lions.dreamhost.com'

#Go talk to 8t88
alias 88='cd /media/8t88'

#plugins
plugins=(git)

#Git Alias
alias git='hub'
alias gx='gitx'
alias ga='git add'
alias gp='git push'
alias gs='git status'
alias gpr='git pull --rebase'
alias gphm='git push heroku master'
alias hr='heroku run'
alias conflicts="git ls-files --unmerged | cut -f2 | uniq | xargs vim"
alias gpu='git push -u origin'

#KILL ALL SWP FILES
alias swpk='rm .*.*.swp'

alias gemgone='gem list | cut -d" " -f1 | xargs gem uninstall -aIx'

alias z='zeus'
#

alias be="bundle exec"
alias bake="bundle exec rake"
alias migrate="bundle exec rake db:migrate db:test:prepare"

alias tks="tmux kill-session -t"
alias tas="tmux attach-session -t"
alias tls="tmux list-sessions"
alias ..='cd ..'

#rsync shortcut
alias rsync="rsync -rzhP"

#pgstarting
alias pgstart="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias pgstop="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log stop"

# Expansions
alias ls='ls -AFGp'
alias tree='tree -aCFl --charset=UTF8 --du --si'

# Tmux Fuckery
alias tmux="tmux -2"

#Bundle
alias vinstall="vim +BundleInstall +qall"
alias vclean="vim +BundleClean +qall"
alias vupdate="vim +BundleUpdate +qall"

export TERM=screen-256color
export EDITOR='vi'

#ChuppAliases
alias gc="git checkout"
alias gcb="git checkout -b"
alias gcm="git commit -m"
alias v="vim"

kill_port() {
   lsof -i tcp:"$*" | awk 'NR!=1 {print $2}' | xargs kill | echo "Killed servers on port $*"
}
#iOS simulator
alias simulator='open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app'

#heroku
alias db_restore='pg_restore --verbose --clean --no-acl --no-owner'

#Ruby Performance Tweaks
export RUBY_HEAP_MIN_SLOTS=1000000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=1000000000
export RUBY_HEAP_FREE_MIN=500000
